/**
 * Article page - displays individual article content.
 */

import { useParams, Link, useNavigate } from '@tanstack/react-router';
import { useState, useEffect, useRef } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { ArrowLeftIcon } from '@heroicons/react/24/outline';
import DOMPurify from 'isomorphic-dompurify';
import { SectionHeading } from '../components/ui';
import {
  TableOfContents,
  FootnotePopup,
  CodeTabs,
  ExpandableCode,
  NCADemo,
  parseCodeTabsData,
  parseExpandableCodeData,
  parseNCAData,
} from '../components/articles';
import { articles } from '../content/registry';
import { enableSmoothScrollForAnchors } from '../lib/scrollTo';
import { BASE_PATH } from '../router';
import type { Article } from '../content/types';

// Import styles
import '../styles/article.css';
import 'katex/dist/katex.min.css';

export default function ArticlePage() {
  const { slug } = useParams({ from: '/resources/$slug' });
  const articleMeta = articles[slug];

  // State for full article content
  const [article, setArticle] = useState<Article | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Ref for article content container (for event delegation)
  const contentRef = useRef<HTMLDivElement>(null);

  // Fetch full article content
  useEffect(() => {
    if (!articleMeta) {
      setIsLoading(false);
      return;
    }

    const fetchArticle = async () => {
      try {
        setIsLoading(true);
        setError(null);

        const response = await fetch(`${BASE_PATH}/articles/${slug}.json`);

        if (!response.ok) {
          throw new Error('Failed to load article');
        }

        const data = await response.json();
        setArticle(data);
      } catch (e) {
        console.error('Error loading article:', e);
        setError(e instanceof Error ? e.message : 'Failed to load article');
      } finally {
        setIsLoading(false);
      }
    };

    fetchArticle();
  }, [slug, articleMeta]);

  // Enable smooth scroll for anchor links
  useEffect(() => {
    const cleanup = enableSmoothScrollForAnchors(contentRef.current, 100);
    return cleanup;
  }, [article]);

  // Intercept internal link clicks for client-side navigation
  const navigate = useNavigate();
  useEffect(() => {
    if (!contentRef.current) return;

    const handleClick = (e: MouseEvent) => {
      const target = e.target as HTMLElement;
      const anchor = target.closest('a');
      if (!anchor) return;

      const href = anchor.getAttribute('href');
      if (!href) return;

      // Only intercept internal links (starting with / but not //)
      if (href.startsWith('/') && !href.startsWith('//')) {
        e.preventDefault();
        navigate({ to: href });
        window.scrollTo(0, 0);
      }
    };

    const container = contentRef.current;
    container.addEventListener('click', handleClick);
    return () => container.removeEventListener('click', handleClick);
  }, [navigate, article]);

  // Track React roots for cleanup
  const reactRootsRef = useRef<Root[]>([]);

  // Hydrate article widgets generated by custom Markdown directives.
  useEffect(() => {
    if (!contentRef.current || !article) return;

    const container = contentRef.current;
    const roots: Root[] = [];

    // Hydrate CodeTabs
    const codeTabsContainers = container.querySelectorAll<HTMLElement>(
      '.code-tabs-container[data-codetabs]'
    );
    codeTabsContainers.forEach((el) => {
      const data = parseCodeTabsData(el);
      if (data) {
        const root = createRoot(el);
        root.render(<CodeTabs blocks={data.blocks} />);
        roots.push(root);
      }
    });

    // Hydrate ExpandableCode
    const expandableContainers = container.querySelectorAll<HTMLElement>(
      '.expandable-code-container[data-expandable-code]'
    );
    expandableContainers.forEach((el) => {
      const data = parseExpandableCodeData(el);
      if (data) {
        const root = createRoot(el);
        root.render(
          <ExpandableCode
            title={data.title}
            code={data.code}
            highlightedHtml={data.highlightedHtml}
            language={data.language}
            defaultOpen={data.defaultOpen}
          />
        );
        roots.push(root);
      }
    });

    // Hydrate NCADemo
    const ncaContainers = container.querySelectorAll<HTMLElement>(
      '.nca-demo-container[data-nca]'
    );
    ncaContainers.forEach((el) => {
      const config = parseNCAData(el);
      if (config) {
        const root = createRoot(el);
        root.render(<NCADemo config={config} />);
        roots.push(root);
      }
    });

    reactRootsRef.current = roots;

    // Cleanup on unmount or article change
    return () => {
      roots.forEach((root) => root.unmount());
      reactRootsRef.current = [];
    };
  }, [article]);

  // 404 for unknown articles
  if (!articleMeta) {
    return (
      <div className="container-era section-spacing">
        <SectionHeading as="h1">Article Not Found</SectionHeading>
        <p className="text-[var(--color-text-secondary)] mb-8">
          The article you're looking for doesn't exist or has been removed.
        </p>
        <Link
          to="/resources"
          className="inline-flex items-center gap-2 text-[var(--color-primary-dark)] font-medium hover:text-[var(--color-primary)] transition-colors"
        >
          <ArrowLeftIcon className="w-[18px] h-[18px]" />
          Back to Resources
        </Link>
      </div>
    );
  }

  return (
    <div className="section-spacing">
      {/* Back Link - outside grid */}
      <div className="container-era mb-6">
        <Link
          to="/resources"
          className="inline-flex items-center gap-2 text-[var(--color-text-muted)] hover:text-[var(--color-text-primary)] transition-colors"
        >
          <ArrowLeftIcon className="w-[18px] h-[18px]" />
          Back to Resources
        </Link>
      </div>

      {/* Mobile Table of Contents */}
      {article && article.tableOfContents.length > 0 && (
        <div className="container-era mb-6 lg:hidden">
          <TableOfContents items={article.tableOfContents} />
        </div>
      )}

      {/* Article Layout with ToC sidebar */}
      <div className="article-layout">
        {/* Article Grid Container */}
        <article className="article-grid">
          {/* Article Header */}
          <header className="article-header" style={{ gridColumn: 'text' }}>
            {/* Status Badge */}
            {articleMeta.status && articleMeta.status !== 'published' && (
              <span className={`article-status ${articleMeta.status}`}>
                {articleMeta.status === 'peer-reviewed'
                  ? 'Peer Reviewed'
                  : articleMeta.status}
              </span>
            )}

            {/* Title */}
            <h1 className="article-title">{articleMeta.title}</h1>

            {/* Subtitle */}
            {articleMeta.subtitle && (
              <p className="article-subtitle">{articleMeta.subtitle}</p>
            )}

            {/* Byline */}
            <div className="article-byline">
              <div className="byline-authors">
                {articleMeta.authors.map((author, i) => (
                  <div key={i} className="byline-author">
                    <span className="byline-author-name">
                      {author.url ? (
                        <a
                          href={author.url}
                          target="_blank"
                          rel="noopener noreferrer"
                        >
                          {author.name}
                        </a>
                      ) : (
                        author.name
                      )}
                    </span>
                    {author.affiliation && (
                      <span className="byline-affiliation">
                        {author.affiliation}
                      </span>
                    )}
                  </div>
                ))}
              </div>

              <div className="byline-meta">
                <time dateTime={articleMeta.date}>
                  {new Intl.DateTimeFormat('en-US', {
                    month: 'long',
                    day: 'numeric',
                    year: 'numeric',
                  }).format(new Date(articleMeta.date))}
                </time>
                <span className="byline-separator" aria-hidden="true">
                  ·
                </span>
                <span>{articleMeta.readingTime} min read</span>
              </div>
            </div>

            {/* Tags */}
            <div className="article-tags">
              {articleMeta.tags.map((tag) => (
                <span key={tag} className="article-tag">
                  {tag}
                </span>
              ))}
            </div>
          </header>

          {/* Article Content */}
          {isLoading ? (
            <div className="article-loading" style={{ gridColumn: 'text' }}>
              <div className="article-loading-spinner" />
              <span>Loading article...</span>
            </div>
          ) : error ? (
            <div
              className="p-8 rounded-xl text-center"
              style={{
                gridColumn: 'text',
                background: 'var(--color-surface-alt)',
                borderStyle: 'dashed',
                borderWidth: 2,
                borderColor: 'var(--color-border)',
              }}
            >
              <p className="text-lg font-medium mb-2 text-[var(--color-text-secondary)]">
                Error Loading Article
              </p>
              <p className="text-[var(--color-text-muted)]">{error}</p>
            </div>
          ) : article ? (
            <div
              ref={contentRef}
              className="article-content"
              dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(article.content, {
                ADD_TAGS: ['math', 'mrow', 'mi', 'mo', 'mn', 'msup', 'msub', 'mfrac', 'mtext', 'annotation', 'semantics'],
                ADD_ATTR: ['encoding', 'data-codetabs', 'data-expandable-code', 'data-nca'],
              }) }}
            />
          ) : null}
        </article>

        {/* Desktop Table of Contents - sticky sidebar */}
        {article && article.tableOfContents.length > 0 && (
          <aside className="article-toc-sidebar hidden lg:block">
            <TableOfContents items={article.tableOfContents} />
          </aside>
        )}
      </div>

      {/* Footnote hover popup */}
      {article && <FootnotePopup containerRef={contentRef} />}
    </div>
  );
}
